### ISSUE TITLE
Write working test of Ericscript

### ISSUE THREAD

**Issue by mmterpstra** [mmterpstra/Ericscript#2]
### todo

- [x] automate self install with perl /cpam minus
- [x] install works in .travis.yml
- [ ] write tests for general usage

### optional

- [ ] automate third party tools install
